version: '2'

services:
    php:
        build:
            context: docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./wps:/var/www/weather-api
    nginx:
        build:
            context: docker/nginx
        ports:
            - 8383:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
