version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8383:80"
        volumes:
            - ./wps:/var/www/weather-api
            - ./api.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        image: php:7-fpm
        volumes:
            - ./wps:/var/www/weather-api